### PR TITLE
Fix bad type lookups

### LINKED ISSUE #26: Post endpoint's data object is typed to union of <SomeType> and <SomeType>[]
**Description**

Hi! I'm trying out this package in combination with openapi-typescript. I found that when I tried to POST to my endpoint, let's say `/categories` the type of data is `Category` | `Category[]`, which is weird to me because in my openapi schema, there is no reference to any array being returned from this POST call. What am I doing wrong here?

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #26.

## How to Review

Test added; tests should pass

## Checklist

- [x] Tests updated

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -85,36 +90,36 @@ export default function createClient<Paths extends {}>(options?: ClientOptions)
 
   return {
     /** Call a GET endpoint */
-    async get<Pathname extends PathsWith<Paths, 'get'>>(url: Pathname, init: FetchOptions<FilterKeys<Paths[Pathname], 'get'>>) {
-      return coreFetch(url, { ...init, method: 'GET' } as any);
+    async get<P extends PathsWith<Paths, 'get'>>(url: P, init: FetchOptions<FilterKeys<Paths[P], 'get'>>) {
+      return coreFetch<P, 'get'>(url, { ...init, method: 'GET' } as any);
```
Comment (drwpow) [inline src/index.ts:94]: The issue causing #26 is that somehow, the type inference was “losing” the HTTP Method being used, and would filter _all_ methods under the same URL, which resulted in some confusion.

The “dumb” solution was just declare the URL and HTTP method statically here. Which isn’t a bad thing, because it means TS doesn’t have to do nearly as much work figuring out which URL is being used.

File: test/v1.d.ts [hunk 2]
```diff
@@ -59,7 +72,7 @@ export interface paths {
       };
       requestBody: components["requestBodies"]["PatchPost"];
       responses: {
-        200: copmonents["responses"]["PatchPost"];
```
Comment (drwpow) [inline test/v1.d.ts:62]: oops
