### PR TITLE
Fix TS lib error, simplify generated types

### LINKED ISSUE #14: index.d.ts broken - "Type 'U' cannot be used to index type 'T'."
**Description**

The `index.d.ts` generated for `openapi-fetch` causes (my) Typescript compiler to complain "Type 'U' cannot be used to index type 'T'."

**Reproduction**

* Clean plate
```
git clone https://github.com/drwpow/openapi-fetch.git
git checkout v0.0.6

cd openapi-fetch
npm install
```
* Place attached file [repro.ts.txt](https://github.com/drwpow/openapi-fetch/files/11189773/repro.ts.txt) as `repro.ts` into the root of the repository
* `npx tsc repro.ts`

// exp: no diagnostics
//act:
```
Type 'U' cannot be used to index type 'T'.
Type 'M' cannot be used to index type 'T[U]'.
```

Trigger is the following part in `index.d.ts`:

```typescript
export default function createClient<T>(defaultOptions?: ClientOptions): {
    /** Call a GET endpoint */
    get<U extends { [Path in keyof T]: T[Path] extends {
        get: unknown;
    } ? Path : never; }[keyof T], M extends keyof T[U]>(url: U, options: (T[U][M] extends infer T ? T extends T[U][M] ? T extends {
        parameters: any;
    } ? {
```

### PR DESCRIPTION
**Pull request by drwpow**
## Changes

Fixes #14.

## How to Review

Tests should pass (they’ll catch TS errors)

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -13,8 +13,22 @@ export interface BaseParams {
   query?: Record<string, unknown>;
 }
 
-export const methods = ['get', 'put', 'post', 'delete', 'options', 'head', 'patch', 'trace'] as const;
```
Comment (drwpow) [inline src/index.ts:16]: Deleted this. This was left over from a previous revision and no longer used.

Made the library even smaller 😎
